"""
Base indicator class for AI detection analysis.
All specific indicators inherit from this class.
"""
from abc import ABC, abstractmethod
from typing import Dict, Any


class BaseIndicator(ABC):
    """
    Abstract base class for all AI detection indicators.
    
    Each indicator represents a specific check that can help determine
    if an audio file was generated by AI.
    """
    
    # These should be overridden in subclasses
    name: str = None                    # Unique identifier
    category: str = None                # 'encoding', 'audio', 'codec', 'format', 'size', 'padding'
    weight: int = None                  # Weight in scoring (0-100)
    description: str = None             # Human-readable description
    risk_level: str = None              # 'low', 'medium', 'high'
    
    @abstractmethod
    def check(self, metadata: Dict[str, Any], patterns: Dict[str, Any]) -> Dict[str, Any]:
        """
        Check if this indicator is present in the file.
        
        Args:
            metadata: Dictionary of extracted metadata
            patterns: Dictionary of pattern analysis results
            
        Returns:
            Dictionary with structure:
            {
                'detected': bool,           # True if indicator is present
                'details': {},              # Additional details about the detection
                'reasoning_key': str        # i18n key for the explanation
            }
        """
        pass
