"""
File size indicators for AI detection.
"""
from typing import Dict, Any
from .base_indicator import BaseIndicator


class FileSizeIndicator(BaseIndicator):
    """Detects anomalies in file size based on bitrate and duration.
    
    Weight: 15 (Supporting Factor)
    Uses formula: Expected size = (bitrate × duration_seconds) / 8
    
    Accounts for lossy vs lossless formats:
    - Lossy (MP3, AAC, Opus): allows ±20% deviation
    - Lossless (WAV, FLAC): allows ±5% deviation
    """
    
    name = "file_size"
    category = "size"
    weight = 15 
    description = "Severe inconsistency between file size and its duration/bitrate"
    risk_level = "low"  
    
    def check(self, metadata: Dict[str, Any], patterns: Dict[str, Any]) -> Dict[str, Any]:
        """
        Check if file size matches expected size based on bitrate × duration.
        """
        try:
            file_size = int(metadata.get('file_size_bytes', 0))
            duration = float(metadata.get('ffprobe_format_duration', 0))
            bitrate = int(metadata.get('ffprobe_streams_0_bit_rate', 0))
            file_format = metadata.get('file_format', '').lower()
            
            if duration == 0 or bitrate == 0 or file_size == 0:
                return {
                    'detected': False,
                    'details': {'reason': 'Missing data: duration, bitrate, or size'},
                    'reasoning_key': 'indicators.file_size.reasoning_error'
                }
            
            # Calculate the expected theoretical file size
            expected_size = (bitrate * duration) / 8
            
            lossy_formats = ['mp3', 'm4a']
            is_lossy = any(fmt in file_format for fmt in lossy_formats)
            
            # Tolerance: We are more permissive with lossy formats to avoid false positives
            # generated by Variable Bitrate (VBR) estimation errors
            tolerance = 0.20 if is_lossy else 0.05
            
            deviation = abs(file_size - expected_size) / expected_size if expected_size > 0 else 0
            deviation_percentage = deviation * 100
            
            # Binary Detection: Yes or No based on tolerance threshold
            detected = deviation > tolerance
            
            return {
                'detected': detected,
                'details': {
                    'file_size': file_size,
                    'expected_size': int(expected_size),
                    'bitrate': bitrate,
                    'duration_seconds': duration,
                    'format': file_format,
                    'is_lossy': is_lossy,
                    'deviation_percentage': round(deviation_percentage, 2),
                    'tolerance_percentage': tolerance * 100,
                },
                'reasoning_key': 'indicators.file_size.reasoning_high_deviation' if detected else 'indicators.ok'
            }
            
        except Exception as e:
            return {
                'detected': False,
                'details': {'error': str(e)},
                'reasoning_key': 'indicators.file_size.reasoning_error'
            }