import React, { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { AlertCircle, Music, Download, Loader } from 'lucide-react';
import FileBar from '../components/FileBar';
import RiskScoreCard from '../components/RiskScoreCard';
import IndicatorsGrid from '../components/IndicatorsGrid';
import ConclusionBox from '../components/ConclusionBox';
import { useFiles } from '../context/FileContext';
import { getAnalysis } from '../api/audioService';
import './Common.css';
import './AnalysisPage.css';

const AnalysisPage = () => {
	const { t } = useTranslation();
	const { files, updateFile } = useFiles();
	const [loading, setLoading] = useState(false);
	const [error, setError] = useState(null);
	const [analyzed, setAnalyzed] = useState(false);

	// Get the currently loaded file (first one in the list)
	const currentFile = files.length > 0 ? files[0] : null;

	// Reset analyzed state when file changes
	useEffect(() => {
		setAnalyzed(false);
		setError(null);
	}, [currentFile?.id]);

	const handleAnalyzeAI = async () => {
		if (!currentFile) {
			setError(t('pages.analysis.noFileLoaded') || 'No file loaded');
			return;
		}

		setLoading(true);
		setError(null);

		try {
			const response = await getAnalysis(currentFile.id);
			const analysis = response.data;

			// Update the file in context with analysis
			updateFile(currentFile.id, {
				analysis,
				analysisLoading: false,
				analysisError: null,
			});

			setAnalyzed(true);
		} catch (err) {
			const errorMessage = err.response?.data?.detail || 'Error performing analysis';
			setError(errorMessage);
			updateFile(currentFile.id, {
				analysisError: errorMessage,
				analysisLoading: false,
			});
		} finally {
			setLoading(false);
		}
	};

	const handleExportAnalysis = () => {
        if (!currentFile?.analysis) return;

        const analysisData = {
            filename: currentFile.name,
            timestamp: new Date().toISOString(),
            ...currentFile.analysis,
        };

        const dataStr = JSON.stringify(analysisData, null, 2);
        const dataBlob = new Blob([dataStr], { type: 'application/json' });
        const url = URL.createObjectURL(dataBlob);
        
        const link = document.createElement('a');
        link.href = url;
        // Se asegura de tener un nombre de archivo fallback por si currentFile.id no existe
        link.download = `analysis_${currentFile.id || 'export'}.json`; 
        
        // 1. Añadir el enlace al DOM
        document.body.appendChild(link);
        
        // 2. Simular el clic
        link.click();
        
        // 3. Limpiar: remover del DOM y revocar la URL
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

	return (
		<>
			<FileBar />
			<section className="page-card">
				<h3>{t('pages.analysis.title') || 'AI Detection Analysis'}</h3>
				<p>{t('pages.analysis.description') || 'Comprehensive analysis to determine if audio was generated by artificial intelligence.'}</p>

				{/* No file loaded message */}
				{!currentFile && (
					<div className="analysis-no-file">
						<Music size={48} />
						<p>{t('pages.analysis.noFileMessage') || 'Load a file in the audio ingestion section first.'}</p>
					</div>
				)}

				{/* File loaded section */}
				{currentFile && (
					<div className="analysis-section">
						<div className="analysis-file-info">
							<div className="analysis-file-name">
								<Music size={20} />
								<span>{currentFile.name}</span>
							</div>
							<button
								className={`analysis-analyze-button ${loading ? 'analysis-analyze-button--loading' : ''}`}
								onClick={handleAnalyzeAI}
								disabled={loading}
							>
								{loading ? (
									<>
										<Loader size={18} className="spinner" />
										{t('pages.analysis.analyzing') || 'Analyzing...'}
									</>
								) : (
									t('pages.analysis.analyzeButton') || 'Analyze for AI'
								)}
							</button>
						</div>

						{/* Error message if analysis failed */}
						{error && (
							<div className="analysis-error-banner">
								<AlertCircle size={20} />
								<span>{error}</span>
							</div>
						)}

						{/* Display analysis results if available */}
						{currentFile.analysis && !loading && !error && (
							<div className="analysis-results">
								{/* Risk Score Card */}
								<RiskScoreCard
									score={currentFile.analysis.risk_score}
									likelihood={currentFile.analysis.likelihood}
									color={currentFile.analysis.score_color}
								/>

								{/* Indicators Grid */}
								<IndicatorsGrid
									detectedFactors={currentFile.analysis.detected_factors}
									missingFactors={currentFile.analysis.missing_factors}
								/>

								{/* Conclusion Box */}
								<ConclusionBox
									riskScore={currentFile.analysis.risk_score}
									likelihood={currentFile.analysis.likelihood}
									conclusionKey={currentFile.analysis.conclusion_key}
									recommendations={currentFile.analysis.recommendations}
								></ConclusionBox>

								{/* Export Button */}
								<div className="analysis-export">
									<button 
										className="analysis-export-button"
										onClick={handleExportAnalysis}
									>
										<Download size={18} />
										{t('pages.analysis.exportButton') || 'Export Analysis'}
									</button>
								</div>
							</div>
						)}

						{/* Show loading spinner if fetching */}
						{loading && (
							<div className="analysis-loading">
								<Loader size={48} className="spinner" />
								<p>{t('pages.analysis.analyzing') || 'Analyzing file...'}</p>
							</div>
						)}

						{/* Show message when no analysis has been performed yet */}
						{!currentFile.analysis && !loading && !error && (
							<div className="analysis-empty">
								<AlertCircle size={48} />
								<p>{t('pages.analysis.emptyMessage') || 'Click "Analyze for AI" to start the analysis'}</p>
							</div>
						)}
					</div>
				)}
			</section>
		</>
	);
};

export default AnalysisPage;
